# Generated by Django 2.1.7 on 2019-03-26 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('ABUSE', 'Abuse'), ('ARREST', 'Arrest'), ('ARSON', 'Arson'), ('ASSAULT', 'Assault'), ('BURGLARY', 'Burglary'), ('EXPLOSION', 'Explosion'), ('FIGHTING', 'Fighting'), ('ACCIDENTS', 'Road Accidents'), ('ROBBERY', 'Robbery'), ('SHOOTING', 'Shooting'), ('SHOPLIFTING', 'Shoplifting'), ('STEALING', 'Stealing'), ('VANDALISM', 'Vandalism'), ('NORMAL', 'Normal event')], max_length=250)),
                ('timestamp', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('PERSONNEL', 'Personnel')], max_length=20)),
                ('cameras', models.ManyToManyField(related_name='persons', to='notifications.Camera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
