# Generated by Django 2.2.1 on 2019-05-07 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_person_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='enable_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
